title: Test-for-test
#author:
  #name: GitHub User
 # email: your-email@domain.com

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  
email: dmistep@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Мои шпаргалки для вэб разработки, сетей и операционных систем.
baseurl: "/test-for-test" # the subpath of your site, e.g. /blog
url: "https://dmistep.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  dmistep

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true
permalink: /:collection/:year-:month-:day-:title:output_ext 


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
markdown: kramdown
#theme: flex

plugins:
 - jekyll-feed
# - jekyll-seo-tag

top-menu:
- url: test.html
  name: HTML
- url: #
  name: CSS
- url: #
  name: Linux
- url: #
  name: Windows
- url: #
  name: Администрирование



links-CheatSheet:
 - url: blog.html
   name: Мои посты
   memo: – шпаргалка по HTML и CSS
 - url: https://adam-marsden.co.uk/css-cheat-sheet
   name: CSS Cheat Sheet
   memo: – шпаргалка по CSS
 - url: http://jquery.page2page.ru/
   name: jQuery page2page
   memo: – шпаргалка по jQuery
 

