title: Общий привет
links-CheatSheet:
 - url: blog.html
   name: Мои посты
   memo: – шпаргалка по HTML и CSS
 - url: https://adam-marsden.co.uk/css-cheat-sheet
   name: CSS Cheat Sheet
   memo: – шпаргалка по CSS
 - url: http://jquery.page2page.ru/
   name: jQuery page2page
   memo: – шпаргалка по jQuery
 
markdown: kramdown
theme: minima
future: tru
