title: Общий привет
links:
 - url: http://htmlbook.ru/css-cheat-sheet
   name: HTML Book
   memo: – шпаргалка по HTML и CSS
 - url: https://adam-marsden.co.uk/css-cheat-sheet
   name: 
 

theme: jekyll-theme-minimal